image: 'ruby:2.6.5'


cache:
  paths:
    - vendor/ruby
    - node_modules


before_script:
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get install -y nodejs
  - apt-get install -y npm
  - gem install bundler --conservative --no-ri --no-rdoc
  - bundle install
  - npm install -g yarn
  - yarn install


stages:
  - lint
  - test


lint:
  stage: lint
  script:
    - bin/lint --no-fix


test:
  stage: test
  variables:
    MYSQL_HOST: 'mysql'
    MYSQL_DATABASE: 'hope_test'
    MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    SYSTEM_EMAIL: 'test@example.com'
    REDIS_URL: 'redis://redis:6379/'
  services:
    - redis:latest
    - name: mysql:latest
      command: ['--default-authentication-plugin=mysql_native_password']
  script:
    - bin/rails db:setup RAILS_ENV=test
    - bin/rails test
