website_name: WITHWomen Pathways
website_desc: Pathways is a website that provides tailored information for taking action around safety.

email_name: WITHWomen
email_from: noreply@withwomen.ca
email_to:   withwomen@smh.ca